# Site settings
title: Yuri Withowsky
email: yuriwithowsky@outlook.com
baseurl:
url: "https://yuriwithowsky.github.io"
encoding: "utf-8"

# Author settings
social:
    - title: facebook
      url: https://www.facebook.com/YuriWithowsky
    - title: github
      url: https://www.github.com/yuriwithowsky
    - title: behance
      url: https://www.behance.net/YuriWithowsky
    - title: linkedin
      url: https://www.linkedin.com/in/YuriWithowsky
    
navigation:
    - title: Projects
      url: /index.html
    - title: Contact me
      url: /contact.html
      
# Build settings
markdown: kramdown
