# Site settings
title: Yuri Withowsky
email: yuriwithowsky@outlook.com
baseurl: "/"
url: "http://yuriwithowsky.github.io"

# Author settings
social:
    - title: facebook
      url: www.tis.com
    
# Build settings
markdown: kramdown
