# Site settings
title: Yuri Withowsky
email: yuriwithowsky@outlook.com
baseurl: "/"
url: "http://yuriwithowsky.github.io"

# Author settings
social:
    - title: facebook
      url: https://www.facebook.com/YuriWitkowsky
    - title: github
      url: http://www.github.com/yuriwithowsky
    - title: behance
      url: http://www.behance.net/YuriWithowsky
    - title: linkedin
      url: http://www.linkedin.com/in/YuriWithowsky
    
# Build settings
markdown: kramdown
