# Site settings
title: Yuri Withowsky
email: yuriwithowsky@gmail.com
baseurl:
url: "https://yuriwithowsky.com"
encoding: "utf-8"

# Author settings
social:
    - title: Canal no YouTube
      icon: youtube
      url: https://www.youtube.com/c/YuriWithowsky
    - title: Perfil no GitHub
      icon: github
      url: https://www.github.com/yuriwithowsky
    - title: Perfil no X
      icon: x
      url: https://www.x.com/YuriWithowsky
    - title: Perfil no LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/YuriWithowsky
    
navigation:
    - title: Projects
      url: /index.html
    - title: Contact me
      url: /contact.html
      
# Build settings
markdown: kramdown
