# Site settings
title: Yuri Withowsky
email: yuriwithowsky@outlook.com
baseurl:
url: "https://yuriwithowsky.com"
encoding: "utf-8"

# Author settings
social:
    - title: youtube
      url: https://www.youtube.com/c/YuriWithowsky
    - title: github
      url: https://www.github.com/yuriwithowsky
    - title: x
      url: https://www.x.com/YuriWithowsky
    - title: linkedin
      url: https://www.linkedin.com/in/YuriWithowsky
    
navigation:
    - title: Projects
      url: /index.html
    - title: Contact me
      url: /contact.html
      
# Build settings
markdown: kramdown
