# Site settings
title: Yuri Withowsky
email: yuriwithowsky@outlook.com
baseurl: "/"
url: "http://yuriwithowsky.github.io"

# Author settings
social:
    - title: facebook
      url: www.facebook.com/YuriWitkowsky
    - title: github
      url: www.github.com
    
# Build settings
markdown: kramdown
